### ISSUE TITLE
An issus around your plugin and my little project

### ISSUE THREAD

**Issue by coussini** [KillerBOSS2019/TouchPortal-API#25]
Hi KillerBOSS2019:

I spoke on this problem in the Discord Touch Portal, and the people said that's an issus.

So, there is the problem:

### I created a button with "ON PRESSED EVENT" (according to the plugin.py and entry.tp bellow) 

**This event is :** Set Variable Named: $(value:Ext_power) to Value: 1

### Explanation of this problem

Hi, I try do build a little plugin for X-PLane Simulation to test my "TP comprehension" and I had this problem when I press this created button on the first time. When I pressed this button a second time, everything is ok. 

### What's I missing. 

**(I USED SUBLIME TEXT TO MONITORING THE PLUGIN.PY EXECUTION. THAT'S WHAT I GET).** 

You can see in the following, my plugin.py, entry.tp and also a [Traceback]

THANKS !

### [plugin.py]
import TouchPortalAPI as TP

**Setup callbacks and connection**
TPClient = TP.Client("XPlanePlugin")

**This event handler will run once when the client connects to Touch Portal**
@TPClient.on('info')
def onInfo(data):
    print("Connected!")
    print("TP returned:")
    print(data)
    TPClient.createState("Ext_power","External Power","AirbusFBW_ElecOHPArray3")

**Action handlers, called when user activates one of this plugin's actions in Touch Portal.**
@TPClient.on('action')
def onAction(data):
    print("Action catch!")
    print("TP returned:")
    print(data)
    print(TPClient.currentStates)
    # stateId = data["data"][0]["value"]
    # print(stateId)

**ListChange handlers, called when user activates one of this plugin's actions in Touch Portal.**
@TPClient.on('listChange')
def onAction(data):
    print("ListChange catch!")
    print("TP returned:")

**Shutdown handler, called when Touch Portal wants to stop your plugin.**
@TPClient.on('closePlugin')
def onShutdown(data):
    print("Got Shutdown Message! Shutting Down the Plugin!")
    **Terminates the connection and returns from connect()**
    TPClient.disconnect()

**First Method call**
TPClient.connect()

### [entry.tp]
{
  "sdk": 3,
  "version": 100,
  "name": "XPlane Touch Portal Plugin",
  "id": "XPlanePlugin",
  "configuration": {
    "colorDark": "#212121",
    "colorLight": "#0090ff",
    "parentCategory" : "game"    
  },
  "categories": [
    {
      "id": "XPlanePlugin.Dataref",
      "name": "XPlane - Dataref",
      "imagepath": "%TP_PLUGIN_FOLDER%X-Plane-TouchPortal-Plugin/xplane.png",      
      "actions": [
        {
          "id": "XPlanePlugin.Dataref.TwoStates",
          "name": "This Toggle 2 States Button",
          "prefix": "XPlane",
          "type": "communicate",
          "tryInline": true,
          "hasHoldFunctionality": false,
          "description": "",
          "format": "Toggle {$XPlanePlugin.Dataref.TwoStates.Choice$}",
          "data": [
            {
              "id": "XPlanePlugin.Dataref.TwoStates.Choice",
              "type": "text",
              "label": "Choice",
              "default": "Ext_power"
            }
          ]
        },
        {
          "id": "XPlanePlugin.Dataref.SetVariable",
          "name": "Set Named Variable Value",
          "prefix": "XPlane",
          "type": "communicate",
          "tryInline": true,
          "hasHoldFunctionality": true,
          "description": "",
          "format": "Set Variable Named:{$XPlanePlugin.Dataref.SetVariable.VarName$} to Value:{$XPlanePlugin.Dataref.SetVariable.Value$}",
          "data": [
            {
              "id": "XPlanePlugin.Dataref.SetVariable.VarName",
              "type": "text",
              "label": "Variable Name",
              "default": ""
            },
            {
              "id": "XPlanePlugin.Dataref.SetVariable.Value",
              "type": "text",
              "label": "Value",
              "default": "0"
            }
          ]
        }
      ]
    }
  ],
  "settings": [
    {
      "name": "XPlaneFolder",
      "type": "text",
      "default": "C:/X-Plane 12",
      "maxLength": 255,
      "isPassword": false,
      "readOnly": false
    }
  ]
}

### [TRACEBACK]
Connected!
TP returned:
{'settings': [{'XPlaneFolder': 'C:/X-Plane 12'}], 'tpVersionString': '3.1.6.0.0', 'pluginVersion': 100, 'tpVersionCode': 301006, 'sdkVersion': 6, 'type': 'info', 'status': 'paired'}
09:00:39.085 [I] [client.py:322] Exception in client event loop: KeyError('XPlanePlugin.Dataref.SetVariable')
09:00:39.085 [I] [client.py:297] XPlanePlugin Disconnected from TouchPortal
Got Shutdown Message! Shutting Down the Plugin!
09:00:39.086 [C] [client.py:326] KeyError('XPlanePlugin.Dataref.SetVariable')
Traceback (most recent call last):
  File "C:\Users\couss\AppData\Roaming\TouchPortal\plugins\X-Plane-TouchPortal-Plugin\plugin.py", line 38, in <module>
    TPClient.connect()
  File "C:\Program Files\Python310\lib\site-packages\TouchPortalAPI\client.py", line 619, in connect
    self.__run()  # start the event loop
  File "C:\Program Files\Python310\lib\site-packages\TouchPortalAPI\client.py", line 255, in __run
    self.__die(f"Exception in client event loop: {repr(e)}", e)
  File "C:\Program Files\Python310\lib\site-packages\TouchPortalAPI\client.py", line 327, in __die
    raise exc
  File "C:\Program Files\Python310\lib\site-packages\TouchPortalAPI\client.py", line 245, in __run
    self.__processMessage(line)
  File "C:\Program Files\Python310\lib\site-packages\TouchPortalAPI\client.py", line 267, in __processMessage
    del self.__heldActions[aid]
KeyError: 'XPlanePlugin.Dataref.SetVariable'
[Finished in 3.6s]

**Comment by mpaperno** [comment]
The issue has nothing to do with this API.  Your code crashed inside the message event handler with

`KeyError('XPlanePlugin.Dataref.SetVariable')`

Since you didn't handle the error (in code I mean, eg. try/catch) the TP Client can't do anything but exit.

-Max

**Comment by coussini** [comment]
I find the error. That's a garbage into a tml file (PAGES).

I delete these page and create a new one... and it's working !
