### ISSUE TITLE
example_build.py

### ISSUE THREAD

**Issue by coussini** [KillerBOSS2019/TouchPortal-API#27]
You have to add this following,  after line 106 of example_build.py

**ADDITIONAL_TPPSDK_ARGS = []**

Without this, there is an error.

**Comment by KillerBOSS2019** [comment]
Do you want to add it to your PR that you just send?

**Comment by coussini** [comment]
This is the purpose of my last PR. Your can see in my pull request, that's the purpose is:

**"you have to add ADDITIONAL_TPPSDK_ARGS = [] into example_build.py"**
