### ISSUE TITLE
Removing socket object from event listener callbacks

### ISSUE THREAD

**Issue by mpaperno** [KillerBOSS2019/TouchPortal-API#8]
I'm not sure why the socket was being passed there in the first place... seems like a very bad idea to actually use that socket for anything in a listener callback.

Clearly it's easy to modify the `emit` calls to omit this parameter, but of course it would break any existing code using the API.  I've already done this in the version I'm currently actually using, but it would be nice to fix the API going forward (and probably better sooner than later). 

Perhaps make the change and call it version 2?  Other thoughts?

Thanks,
-Max

**Comment by KillerBOSS2019** [comment]
tbh I don't know why I started passed the socket object in the even listener but from what I see I've never used so it's not a bad idea to remove it

**Comment by KillerBOSS2019** [comment]
we can simply remove it but I also wanted to add a way to Auto generate the entry.tp file then call it V2 that's my thoughts but i havent figured out a way to Auto Generate the entry.tp yet...

**Comment by mpaperno** [comment]
Sounds reasonable.  Removing is just a 2-line [change](https://github.com/mpaperno/TouchPortal-API/commit/5c3e56101c036e61c595597c8589f5f082924987) at this point.  I can PR that if you want.  I know the README could use an update as well.

On the generator idea, what would it generate that has to do with the Python API?  Seems like a separate utility maybe?  Or are you thinking something based on dynamic States?

I would think a generator would also need a config to generate from (name, states, actions, etc)... at which point it's pretty much as easy to just create the json .tp in the first place...?   A GUI may make things nicer though.  I'm curious about what you have in mind.

**Comment by mpaperno** [comment]
Ah just saw the new Issue you started about Generator.  I'll check out what that Java one does.

**Comment by KillerBOSS2019** [comment]
Yeah PR would be nice

**Comment by KillerBOSS2019** [comment]
GUI would work But it would be a extra thing that you have to Open and use it would be better if is all and be made in the script itself
